### ISSUE TITLE
Bug : `fluent-ffmpeg` 영상 병합(concatenate) 시 에러 발생

### ISSUE THREAD

**Issue by waveinyu** [Final-healthree/healthree-backend#124]
## **9월 13일**
MVP를 앞두고, 프론트 서버와 연결하기 전에 마지막으로 테스트를 해보는 중 비디오 병합 기능에서 갑작스러운 에러가 발생했다.

- 기능 구현 이래로 영상은 늘 병합이 잘 됐는데, 이번 테스트에서 처음으로 마지막 3번째 영상에서 병합이 되지 않았다.
- @phenomenonlee님과 데모 영상을 찍어 공유했고 병합이 되는 영상과 되지 않는 영상의 차이를 구분했다.
- 이 과정에서 우리는 병합이 되는 영상과 그렇지 않은 영상의 차이가 **`Dolby Vision`** 란 걸 알게 됐고, **`Dolby Vision`** 이더라도 같은 **`Dolby Vision`** 끼리는 영상 병합이 되는 것을 확인했다.
- 따라서, 병합하고자 하는 영상의 형식이 하나라도 다른 경우 병합이 되지 않는다고 추론할 수 있었다.
  <br>

<details>
<summary>이미지 열기</summary>
<div markdown="1">
<img src="https://user-images.githubusercontent.com/99732695/191316383-8d49c298-cdfd-44d8-81ec-e06d1ba072c4.png" width=400px>
<img src="https://user-images.githubusercontent.com/99732695/191316395-a0125358-ed9d-4da4-9199-6ca0f775d546.png" width=400px>
</div>
</details>

추론을 바탕으로 우리가 실행할 수 있는 방법은 2가지로 보였다.

먼저 업로드 된 영상을 console.log()로 확인하여 어떤 속성이 `Dolby Vision` 을 나타내는지 차이점을 찾아낸 뒤,

1. `Dolby Vision`인 영상은 예외로 처리한다.
   - `Dolby Vision` 은 아이폰 기준 2020년 10월 아이폰12 출시 이후에 탑재한 기능이라 인코딩을 하려면 다운그레이드를 해야 한다는 단점이 있기 때문에, 이는 비효율적이라 판단하여 예외 처리로 진행하고자 했다.
   - 즉, 유저가 같은 형식의 비디오를 업로드 할 수 있게 하고자 했다.
2. 제 3의 형식으로 비디오 3개를 모두 인코딩을 해준다.
   - 영상 3가지 중, 2가지가 같은 형식의 영상이어도 마지막 하나가 다르다면 발생하는 에러였기 때문에 모든 영상을 인코딩하는 건 속도 측면에서도 그렇고 여러 지점에서 서버 자원의 낭비라는 의견을 나누었다.
   - 따라서 제일 후순위로 미뤄놓았다.
3. 백엔드는 아니지만, 1의 과정을 프론트에서 예외를 처리해줄 수 있는지 한 번 논의를 해보잔 의견을 나눴다.

---

**Comment by waveinyu** [comment]
<details>
<summary>슬랙에 남겼던 질문과 답변</summary>
<div>
<img src="https://user-images.githubusercontent.com/99732695/190675240-0356b02b-a18e-4870-aa29-4248ad7c3d87.png" width=70%>
<img src="https://user-images.githubusercontent.com/99732695/190679550-829bd125-ff5e-41a2-8132-56742501a36b.png" width=70%>
</div>
</details>

해결까지는 아니지만, 위의 질의응답으로 대안책을 찾을 수 있었다. ffmpeg와 ffmpeg-concat을 기반으로 한 `editly`란 라이브러리로 너무나 간단히 해결했다.

`editly` 는 가장 최신 버전이 현재(9/21) 기준 23일 전에 업데이트 된 최신 라이브러리다. 일종의 확장팩 개념으로 이해했다. 구글링으로는 정보가 찾기가 쉽지 않았고, 대부분의 정보는 공식 깃허브에서 얻을 수 있었다.

기능 자체는 현재 다시 구현이 되어서 프로젝트를 진행 중이다. 하지만 근본적인 해결이 아니어서 아쉬움이 남는다.

**Comment by phenomenonlee** [comment]
프로젝트가 끝난 후 리팩토링을 통한 원인 발견하게 되었다.
초반에 생각했던 비디오의 코덱과 해상도 차이라는 것을 발견하게 되었다.

모든 비디오 코덱과 해상도 크기를 맞추고 인코딩을 한 다음 병합을 하게 되면 원래는 병합이 안되던 비디오들이 
fluent-ffmpeg로도 병합이 잘 되는 것을 확인 할 수 있었다.

따라서 비디오의 코덱과 해상도 차이가 원인이었다는 것을 알게 되었다.

초반에 모든 비디오를 인코딩하는 방식을 채택하지 않은 이유는 모든 비디오를 인코딩하게 되면 리소스 낭비가 
있을 것이라는 생각이 있었기 때문이다. 

하지만 모든 비디오를 인코딩함으로 비디오의 크기가 대략 35% 감소하였고 비디오 병합시간이 50% 감소하였다.
그렇기에 리소스 낭비가 아닌 **트레이드 오프**로 

1) 각 비디오에 크기를 줄이는 대신에 인코딩 시간이 생겼다.
 유저 입장에서 3초의 인코딩 시간이 생겼지만 유저 경험측면으로 나쁜 영향을 미치지 않을 것이라 생각했다. 

2) 비디오 크기를 줄였기 때문에 비디오 병합 시간이 감소하였다. 
각 비디오를 인코딩 한 시간과 병합한 시간을 합친 것이 인코딩을 안하고 비디오를 병합한 시간이랑 비슷하였다. 

3) 따라서 비디오 처리에 대한 모든 시간은 변동이 없지만 비디오 크기는 줄이게 되었고, 병합시간도 감소하게 되었으며 editly를 사용했을 때는 오디오가 나오지 않는 이슈가 있었지만 그 부분도 해소하게 되었다.
