### ISSUE TITLE
Bug : `Sequelize` 작동 시 에러 발생

### ISSUE THREAD

**Issue by waveinyu** [Final-healthree/healthree-backend#15]
> 9월 2일 <br>
> 디렉토리 및 DB 초기 세팅 후 첫 작업 시 발생한 `Sequelize` 에러입니다.

<br>
@phenomenonlee님이 db 작업 중 아래의 에러 메시지와 함께 `Sequelize`가 진행 되지 않는 걸 확인했습니다.

<br>

```javascript
TypeError: Cannot read properties of undefined (reading 'length')
at Ing._initValues (C:\Users\flejd\Documents\실전프로젝트\healthree-backend\`node_modules\sequelize\lib\model.js:130:49`)
```

에러가 발생한 경로와 에러 메시지로 미루어 짐작해 볼 때, `create()`를 하고자 하는 값이 제대로 읽히지 않았던 것 같았습니다.

<br>

하지만 생성하고자 하는 값의 타입이 모델에서 명시한 유형과 일치하지 않는 등 값에 관련한 문제라면 그에 맞는 에러가 발생했을 거란 얘기를 @phenomenonlee님과 나눴고, 값이 아닌 `Sequelize` 패키지 혹은 그와 `models` 간의 문제일 거라 판단했습니다.

<br>

여러가지 시도를 하던 와중에 에러 메시지가 다음과 같이 변하는 걸 확인했습니다.

```javascript
Sequelize TypeError: Cannot convert undefined or null to object
```

넣으려는 값은 동일했기 때문에 값이 undefined나 null일이 없었습니다. 아울러 `Can not convert`를 보아 좀 더 좁혀 `Sequelize`의 연결 문제일 것이라 생각했습니다.

---

해결은 생각보다 간단했습니다.
<br>

매번 `migrate` 및 `migrate:undo`를 하지 않고 `sync`로 테이블을 제어하는 부분을 `app.js`에서 `db_init.js`로 분리하는 과정에서 `app.js`에 import만 한 채로 `Sequelize` 선언을 빠트렸기 때문이었습니다.

```javascript
// db_init.js
import { sequelize } from "./src/models/index.js";
sequelize // Sequelize 선언
  .sync({ force: true })
  .then(() => console.log("db connect"))
  .catch((err) => console.error(err));
```

```javascript
// app.js
...
import { sequelize } from "./models/index.js";

// sequelize 선언
sequelize;
console.log("db 연결", sequelize.config.port);
```

위와 같이 sequelize를 선언해준 뒤, db가 정상 연결되는지 `console.log()`로 확인한 후 정상적으로 연결되는 것을 확인할 수 있었습니다.

**Comment by phenomenonlee** [comment]
확인했습니다.
